### ISSUE TITLE
Feature request: "Subtitles" mode

### ISSUE THREAD

**Issue by bajosoto** [aviwad/LyricFever#21]
Awesome work! I've only been using it for 30 minutes and I already love your app. One feature I would love to have would be displaying the lyrics as "subtitles", similar to how LyricsX does. That is, "floating", windowless text that can be dragged around the screen and displays on top of all other apps.

**Comment by aviwad** [comment]
Sure. I'll take a look after my exams. Thanks for the feedback 😊. Please share it with your friends and star it on GitHub.

**Comment by aviwad** [comment]
Will be done this month, very close to getting it working :)

**Comment by aviwad** [comment]
<img width="658" alt="image" src="https://github.com/user-attachments/assets/616cc5df-e251-4363-8617-5ffc323a5fa2">


Ironing the bugs out

**Comment by bajosoto** [comment]
It's looking great! Can't wait to try it :)

**Comment by aviwad** [comment]
@bajosoto Here is a beta version compiled. Would love your feedback. I get the album art color from Spotify and set it to the background of the subtitle. Let me know if you think I should reduce/increase opacity, or if you have any other thoughts. It is quite glitchey right now:  
The Fullscreen feature is also new, and so is translate (and so is setting a delay for spotify connect)
[Lyric Fever.zip](https://github.com/user-attachments/files/17595711/Lyric.Fever.zip)

**Comment by bajosoto** [comment]
Hey @aviwad, sorry for the late response. I've been using version 2.0 for a while and I'm loving it! Using the artwork colour was a nice touch. The only feedback I have about the new feature would be that it would be nice to be able to customise the font size, and perhaps the opacity of the background. I haven't needed to add delay for Spotify connect, everything always seems to be in sync for me, but that's also a nice feature to have for whenever it is needed :)
Thanks again for all the effort!
