### ISSUE TITLE
Don't show lyrics

### ISSUE THREAD

**Issue by xzy0601** [aviwad/LyricFever#40]
Does this require Spotify Premium? Or is there a bug in Mac OS 15 beta that doesn't show lyrics?
Please take a look, thank you

**Comment by aviwad** [comment]
Sorry I cannot try macOS 15 beta right now. Pls try running Lyric Fever from the terminal and paste the output. Thanks.

**Comment by xzy0601** [comment]
It's a problem with mac os15. After the beta3 update, the lyrics are displayed.
