### ISSUE TITLE
No Lyrics Found

### ISSUE THREAD

**Issue by nasucase** [aviwad/LyricFever#59]
Hi, i discovered this amazing app couple month ago, and i noticed that the lyric doesnt show up. 
![image](https://github.com/user-attachments/assets/e39923ea-6c64-4075-91c6-a18a6f53df0a)

im currently running on macos sequoia 15.0.1. Running the application from terminal give these results:
![image](https://github.com/user-attachments/assets/7b865fb1-f4e0-422a-b13d-d4e4e4635781)

Thanks in advance :D

**Comment by aviwad** [comment]
So bizarre, I just tried the track ID and it worked on my build. Are you on a Spotify free account?

**Comment by nasucase** [comment]
Yes, I did not pay for premium.

**Comment by aviwad** [comment]
Hmm.. Spotify said they would remove the lyrics restriction but unfortunately they have not complied.... is it possible for you to DM me your api key somewhere so I can test it? Can you dm on GitHub? Or email me at aviwad@gmail.com?

**Comment by aviwad** [comment]
Meanwhile I am working on adding alternate free lyric providers

**Comment by nasucase** [comment]
Sure, i will dm you on github. looking forward to see the new lyric provder work!

**Comment by aviwad** [comment]
My bad I think GitHub doesn't have a DM option. You can find your api key by opening Settings, and clicking API Key: Advanced, and copy pasting the key

<img width="812" alt="image" src="https://github.com/user-attachments/assets/c44193d2-d246-482e-93bc-76dd8a206074">

**Comment by aviwad** [comment]
This key was generated when you logged into Spotify. I'll just try to see if I'm able to fetch lyrics using your key. Is this only a problem for this particular song? Have you been able to load lyrics for other songs?

**Comment by nasucase** [comment]
As of now all songs in my playlist doesnt show lyrics on the application, i have tried the song that is on the promotion video and the issue persists.

**Comment by aviwad** [comment]
[Lyric Fever.zip](https://github.com/user-attachments/files/17810607/Lyric.Fever.zip)

Hey, please try this before I push an update :) it uses LRCLIB as a backup lyrics source

**Comment by aviwad** [comment]
Fixed in version 2.0 please update :)
